server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # امنیت
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    location / {
        # Updated برا html ها
        try_files $uri $uri.html $uri/ /index.html;
        add_header Cache-Control "public, max-age=0, must-revalidate";
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}